# Generated by Django 4.2.29 on 2026-03-30 11:05

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='expires_at',
            field=models.DateTimeField(verbose_name=authentication.models.get_default_expiry),
        ),
    ]
