# Generated by Django 4.2.29 on 2026-04-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_customuser_full_name_customuser_discipline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('LEARNER', 'Learner'), ('INSTRUCTOR', 'Instructor')], default='LEARNER', max_length=20),
        ),
    ]
